name: Update Oil Price Calendar

on:
  schedule:
    - cron: '0 0 1 1 *' # 每年1月1日00:00 UTC运行一次
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update Oil Price Calendar
      run: |
        python update_oil_price_calendar.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add oil_price_adjustment.ics
        git commit -m "Update iCalendar file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
